test values: ./runTests.py -F --ndim 3
{'ndim': 3, 'x': None, 'seed': None, 'flat': (False, False, False), 'new': False}
....................................F....FF.F.FF.....F.F............F...F......................F.F....................F.
======================================================================
FAIL: testParadoxes (unitTests.inversionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 537, in testParadoxes
    self.assertTrue( (self.A & ~self.A) == Mvar(mean=self.A.mean, vectors=self.A.vectors, var=Matrix.infs) )
AssertionError: False is not true

======================================================================
FAIL: testKnownValues3 (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 619, in testKnownValues3
    self.assertTrue( (L1&L2).mean==[0,1])
AssertionError: False is not true

======================================================================
FAIL: testNotFlat (unitTests.blendTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 585, in testNotFlat
    self.assertTrue( self.A & -self.A == Mvar(mean=numpy.zeros(self.ndim))**-1)
AssertionError: False is not true

======================================================================
FAIL: testGivenLinear (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 435, in testGivenLinear
    self.assertTrue( (L1&L2).mean==[1,1] )
AssertionError: False is not true

======================================================================
FAIL: testGivenScalar (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 423, in testGivenScalar
    self.assertTrue( a.mean[:,0]==1 )
AssertionError: False is not true

======================================================================
FAIL: testGivenVector (unitTests.givenTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 445, in testGivenVector
    self.assertTrue( mvar.givenVector(self.A,index=0,value=1)==self.A.given(index=0,value=1) )
AssertionError: False is not true

======================================================================
FAIL: testInfs (unitTests.creationTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 68, in testInfs
    self.assertTrue( inf.var.size==inf.mean.size==n )
AssertionError: False is not true

======================================================================
FAIL: testAnd (unitTests.chainTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/suki/Tutorials/personal-projects/mvar/unitTests.py", line 508, in testAnd
    self.assertTrue(measured[:self.ndim] == self.A&self.B)
AssertionError: False is not true

======================================================================
FAIL: __and__ (__init__.Mvar)
Doctest: __init__.Mvar.__and__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__and__
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1362, in __and__

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1391, in __init__.Mvar.__and__
Failed example:
    if not A.flat:
        assert A &-A == Mvar(mean=numpy.zeros(ndim))**-1
        assert A &~A == Mvar(mean=numpy.zeros(ndim))**-1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[3]>", line 2, in <module>
        assert A &-A == Mvar(mean=numpy.zeros(ndim))**-1
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1421, in __init__.Mvar.__and__
Failed example:
    assert (L1&L2).mean==[0,1]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[17]>", line 1, in <module>
        assert (L1&L2).mean==[0,1]
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1422, in __init__.Mvar.__and__
Failed example:
    assert (L1&L2).var==1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[18]>", line 1, in <module>
        assert (L1&L2).var==1
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1423, in __init__.Mvar.__and__
Failed example:
    assert (L1&L2).vectors==[1,0]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__and__[19]>", line 1, in <module>
        assert (L1&L2).vectors==[1,0]
      File "<string>", line 2, in __eq__
      File "/home/suki/Tutorials/personal-projects/mvar/matrix.py", line 17, in expandCallable
        fun(self,other)
      File "/home/suki/Tutorials/personal-projects/mvar/matrix.py", line 52, in __eq__
        raise ValueError('shape miss-match')
    ValueError: shape miss-match


======================================================================
FAIL: __invert__ (__init__.Mvar)
Doctest: __init__.Mvar.__invert__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.__invert__
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1274, in __invert__

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1304, in __init__.Mvar.__invert__
Failed example:
    assert (A & ~A) == Mvar(mean=A.mean, vectors=A.vectors, var=Matrix.infs)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[11]>", line 1, in <module>
        assert (A & ~A) == Mvar(mean=A.mean, vectors=A.vectors, var=Matrix.infs)
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 1335, in __init__.Mvar.__invert__
Failed example:
    assert P==(A & ~A)       
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.__invert__[20]>", line 1, in <module>
        assert P==(A & ~A)
    AssertionError


======================================================================
FAIL: given (__init__.Mvar)
Doctest: __init__.Mvar.given
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.given
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 933, in given

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 947, in __init__.Mvar.given
Failed example:
    assert a.mean[:,0]==1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[1]>", line 1, in <module>
        assert a.mean[:,0]==1
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 948, in __init__.Mvar.given
Failed example:
    assert a.vectors[:,0]==numpy.zeros
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[2]>", line 1, in <module>
        assert a.vectors[:,0]==numpy.zeros
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 952, in __init__.Mvar.given
Failed example:
    assert A.rank <= 1
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[4]>", line 1, in <module>
        assert A.rank <= 1
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 963, in __init__.Mvar.given
Failed example:
    assert (L1&L2).mean==[1,1]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[9]>", line 1, in <module>
        assert (L1&L2).mean==[1,1]
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 964, in __init__.Mvar.given
Failed example:
    assert (L1&L2).cov==[[0,0],[0,2]]
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[10]>", line 1, in <module>
        assert (L1&L2).cov==[[0,0],[0,2]]
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 983, in __init__.Mvar.given
Failed example:
    assert A.rank > A.given(0 ,1).rank
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[18]>", line 1, in <module>
        assert A.rank > A.given(0 ,1).rank
    AssertionError
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 990, in __init__.Mvar.given
Failed example:
    !! this is one step from a reverse chain ?
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[21]>", line 1
        !! this is one step from a reverse chain ?
        ^
    SyntaxError: invalid syntax
----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 995, in __init__.Mvar.given
Failed example:
    assert A.given(0).given(0,0) == A.given(0,0)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.given[26]>", line 1, in <module>
        assert A.given(0).given(0,0) == A.given(0,0)
    AssertionError


======================================================================
FAIL: infs (__init__.Mvar)
Doctest: __init__.Mvar.infs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.Mvar.infs
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 405, in infs

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 410, in __init__.Mvar.infs
Failed example:
    assert inf.var.size==inf.mean.size==n
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.Mvar.infs[3]>", line 1, in <module>
        assert inf.var.size==inf.mean.size==n
    AssertionError


======================================================================
FAIL: givenVector (__init__)
Doctest: __init__.givenVector
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for __init__.givenVector
  File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2315, in givenVector

----------------------------------------------------------------------
File "/home/suki/Tutorials/personal-projects/mvar/__init__.py", line 2320, in __init__.givenVector
Failed example:
    assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest __init__.givenVector[0]>", line 1, in <module>
        assert givenVector(A,index=0,value=1)==A.given(index=0,value=1)
    AssertionError


----------------------------------------------------------------------
Ran 120 tests in 1.194s

FAILED (failures=13)
